.travis.yml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
```
=> [GH-83] wrapped binary in ZIP for lambda purposes

.travis.yml, CHANGELOG.md, cmd/backup.go, cmd/repositories.go, cmd/root.go, cmd/upload.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
`--version` will return the version of n3dr.
Fixes #82 
```release-note
```
=> [GH-82] versioning

CHANGELOG.md, cli/backup.go, cmd/root.go
>
> /kind bug
/kind design
> /kind flake
Write shorter units of code.
Fixes #60 #61 
```release-note
```
=> 60 61 short units of code

CHANGELOG.md, cmd/backup.go, cmd/repositories.go, cmd/root.go, cmd/upload.go
>
/kind bug
> /kind design
> /kind flake
Fixes #
Inconsistent help menu
```release-note
```
NONE
=> [GH-98] consistent help menu

.github/ISSUE_TEMPLATE/bug-report.md, cli/main_test.go, cli/upload.go, go.mod, go.sum, integration-tests.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [GH-113] Upload zip files.

cli/backup.go, cli/upload.go, cli/upload_test.go, integration-tests.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [GH-113] code smells

CHANGELOG.md, README.md, cli/backup.go, cli/backup_test.go, cli/repositories.go, cli/upload.go, cmd/backup.go, cmd/repositories.go, integration-tests.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [GH-113] Download of specific artifacts.

CHANGELOG.md, README.md, cli/backup.go, cli/backup_test.go, cli/main_test.go, cli/repositories.go, cli/repositories_test.go, cmd/backup.go, go.sum, integration-tests.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> 137 download folder not cleaned

CHANGELOG.md, README.md, cli/req.go, cmd/root.go, integration-tests.sh, snap/snapcraft.yaml, tests.bats
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [GH-139] Anonymous mode.

CHANGELOG.md, cli/backup.go, snap/snapcraft.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [GH-143] Semi colons not interpreted by some machines.

CHANGELOG.md, cli/repositories.go, cli/repositories_test.go, integration-tests.sh, snap/snapcraft.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [GH-133] Duplicated downloads issue resolved.

CHANGELOG.md, README.md, cli/backup.go, cli/backup_test.go, cli/common.go, cli/common_test.go, cli/main_test.go, cli/repositories_test.go, cmd/backup.go, cmd/repositories.go, cmd/root.go, cmd/upload.go, integration-tests.sh, main.go, snap/snapcraft.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [GH-136] Overwrite default zip file name.

CHANGELOG.md, README.md, cli/common.go, snap/snapcraft.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> 138 permission denied

cli/common.go
/kind flake
Recently we have implemented retry logic for requests. I have set Logger to be `nil` [here](https://github.com/030/n3dr/pull/135/files#r453748475) and now I would like to fix it.
Fixes #153 
- Before (debug enabled):
```
$ ./n3dr-dev-linux -u nexus-backup -n https://wrong_url:444 backup -r repo1,repo2 -d
INFO[0000]/Users/volodymyr.soloviov/workspace/public/n3dr/cmd/root.go:59 n3dr/cmd.configFile() n3drHomeDir: '/Users/volodymyr.soloviov/.n3dr' 
INFO 2020/07/29 11:29:03 Trying to resolve absolute path to /Users/volodymyr.soloviov/.n3dr
INFO 2020/07/29 11:29:03 adding /Users/volodymyr.soloviov/.n3dr to paths to search …
```
=> Better logging for retryablehttp

cli/upload.go
>
> /kind bug
> /kind design
> /kind flake
/kind feature
* Add support for Maven2 repo Android aar extension and Gradle module extension in artifact upload
* Add support for Maven2 repo classifier in artifact upload
* Rewrite code for generating upload parameters
Fixes #
```release-note
Add support for Maven2 repo Android aar extension and Gradle module extension in artifact upload
Add …
```
=> Add support for aar and module extensions; add support for classifier

README.md, cli/npm.go, cli/upload.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> 160 uploads2

.markdownlint.rb, .travis.yml, CHANGELOG.md, README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> 171 markdownlint

cli/upload.go
<!--  Thanks for sending a pull request!  Here are some tips for you:
/kind feature
I need to upload artifacts of any kind (exe, zip, apk, ipa, appx, jar,....) with classifiers.
I just begin in Go language for this PR.
NONE
```release-note
Upload any kind of artifacts
Fix import of artifacts with classifier.
```
=> Fix classifier in upload and allow any kind of artifacts

cli/upload.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> 160 allow any kind of maven artifacts fix

.travis.yml, CHANGELOG.md, integration-tests.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> 179 shellcheck

CHANGELOG.md, build.sh, cli/backup.go, integration-tests.sh, snap/snapcraft.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> 134 archetype catalog does not seem to contain a maven artifact

CHANGELOG.md, build/package/snap/snapcraft.yaml, internal/artifacts/common.go, test/integration-tests.sh, test/tests.bats
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [#205] Resolve 'nexus ip not allowed' issue.

.github/workflows/docker.yml, README.md, internal/artifacts/common.go, internal/artifacts/common_test.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [#205] Resolve merge conflict.

.github/workflows/codecov.yml, .github/workflows/dip.yml, .github/workflows/go.yml, .github/workflows/integration.yml, CHANGELOG.md, Dockerfile, README.md, cmd/n3dr/configLDAP.go, internal/artifactsv2/download.go, internal/config/security/ldap.go, test/integration-tests.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [GH-232] Only download hosted artifacts.

CHANGELOG.md, README.md, build/package/snap/snapcraft.yaml, internal/artifactsv2/upload/upload.go, test/integration-tests.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [GH-228] Upload maven artifacts using repositoriesV2.

.dockerignore, .github/workflows/docker.yml, Dockerfile, README.md, build/package/snap/snapcraft.yaml, docs/CHANGELOG.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [GH-241] Resolve 'version not shown when running docker'.

.github/workflows/sonarcloud.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Exclude internal goswagger folder from Sonar.

.github/workflows/sonarcloud.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> exclude internal goswagger

.github/workflows/dip.yml, .github/workflows/go.yml, Dockerfile, README.md, build/package/snap/snapcraft.yaml, cmd/n3dr/repositoriesV2.go, docs/CHANGELOG.md, internal/app/n3dr/artifacts/common.go, internal/app/n3dr/artifactsv2/download.go, internal/app/n3dr/config/repository/repository.go, internal/app/n3dr/config/repository/repository_test.go, internal/app/n3dr/config/security/anonymous_test.go, internal/app/n3dr/config/security/ldap.go, internal/app/n3dr/config/user/user_test.go, internal/app/n3dr/connection/connection.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#278] Backup a single repository using repositoriesV2.

.github/workflows/gosec.yml, .github/workflows/release.yml, .github/workflows/snapcraft.yml, build/package/snap/snapcraft.yaml, docs/CHANGELOG.md, docs/README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> build(snap): [#290] Stable version 7.

.github/workflows/dip.yml, .github/workflows/release.yml, .github/workflows/snapcraft.yml, docs/CHANGELOG.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#294] Apply auto updates.

.github/workflows/dip.yml, README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#294] Update n3dr version in README.

.github/workflows/go.yml, .github/workflows/integration.yml, .github/workflows/release.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> build: Update CI images to latest.

.github/workflows/dip.yml, configs/.golangci.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#309] Enable bodyclose check and autoupdate gosec.

README.md, build/package/snap/snapcraft.yaml, docs/CHANGELOG.md, docs/README.md, internal/app/n3dr/artifactsv2/download.go, test/integration-tests.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#238] Validate docker params.

.github/workflows/integration.yml, .gitignore, Dockerfile, README.md, build/package/snap/snapcraft.yaml, cmd/n3dr/count.go, cmd/n3dr/repositoriesV2.go, cmd/n3dr/root.go, configs/.golangci.yml, docs/CHANGELOG.md, docs/README.md, internal/app/n3dr/artifactsv2/count/artifacts.go, internal/app/n3dr/artifactsv2/count/artifacts_test.go, internal/app/n3dr/artifactsv2/count/repositories.go, internal/app/n3dr/artifactsv2/count/struct.go, internal/app/n3dr/artifactsv2/download.go, internal/app/n3dr/artifactsv2/name/repositories.go, internal/app/n3dr/artifactsv2/name/struct.go, test/integration-tests.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> feat: [#99][#297] Count number of artifacts and save info to a CSV file.

configs/.golangci.yml, internal/app/n3dr/artifactsv2/artifacts/repository.go, internal/app/n3dr/artifactsv2/count/artifacts.go, internal/app/n3dr/artifactsv2/download.go, internal/app/n3dr/artifactsv2/upload/upload.go, internal/app/n3dr/config/repository/repository.go, internal/app/n3dr/config/security/anonymous.go, internal/app/n3dr/config/security/ldap.go, internal/app/n3dr/config/user/user.go, internal/app/n3dr/s3/aws.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#312] Errorlint.

configs/.golangci.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#311] Durationcheck.

cmd/n3dr/configLDAP.go, cmd/n3dr/sync.go, configs/.golangci.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#312] Gofumpt.

cmd/n3dr/config.go, cmd/n3dr/configLDAP.go, cmd/n3dr/configRepository.go, cmd/n3dr/configUser.go, cmd/n3dr/count.go, cmd/n3dr/repositoriesV2.go, cmd/n3dr/sync.go, configs/.golangci.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#319] Godot.

cmd/n3dr/count.go, cmd/n3dr/repositoriesV2.go, cmd/n3dr/root.go, configs/.golangci.yml, internal/app/n3dr/artifactsv2/download.go, internal/app/n3dr/connection/connection.go, internal/app/n3dr/s3/aws.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#331] Stylecheck.

.github/workflows/dive.yml, .gitignore, test/integration-tests.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#342] Backup integration test.

.github/workflows/dip.yml, .gitignore, README.md, build/package/snap/snapcraft.yaml, cmd/n3dr/configRepository.go, docs/CHANGELOG.md, docs/quickstarts/DOCKER.md, docs/quickstarts/RUBYGEMS.md, docs/quickstarts/snippets/n3dr/BACKUP.md, docs/quickstarts/snippets/n3dr/DOWNLOAD.md, docs/quickstarts/snippets/n3dr/UPLOAD.md, docs/quickstarts/snippets/n3dr/VALIDATE.md, docs/quickstarts/snippets/nexus3/ANOTHERSERVER.md, docs/quickstarts/snippets/nexus3/CLEANUP.md, docs/quickstarts/snippets/nexus3/SERVER.md, internal/app/n3dr/artifactsv2/artifacts/file.go, internal/app/n3dr/artifactsv2/count/artifacts.go, internal/app/n3dr/artifactsv2/download.go, internal/app/n3dr/artifactsv2/upload/upload.go, internal/app/n3dr/config/repository/repository.go, test/integration-tests.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> feat: [#363] Backup and upload of Ruby gems.

.github/workflows/dip.yml, .github/workflows/snapcraft.yml, Dockerfile, cmd/n3dr/configUser.go, configs/k8s/README.md, configs/k8s/kind.yaml, configs/k8s/nexus3.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#378] Change initial admin pass (automatically).

.github/workflows/release.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> build(deps): [#399] V is omitted in upload-release-action.

.github/workflows/integration.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: Ensure that integration tests are skipped on dep updates.

internal/app/n3dr/artifactsv2/upload/upload.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#428] Resolve data race condition in upload.

.github/workflows/go.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#430] Do not run Sonar if dependabot branch.

.github/workflows/go.yml, internal/app/n3dr/artifactsv2/upload/upload.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#430] Use semantic version.

cmd/n3dr/repositoriesV2.go, cmd/n3dr/sync.go, internal/app/n3dr/artifactsv2/count/artifacts.go, internal/app/n3dr/artifactsv2/download.go, internal/app/n3dr/artifactsv2/upload/upload.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#428] Resolve race condition.

.github/workflows/snapcraft.yml, Taskfile.yml, build/package/snap/snapcraft.yaml, docs/CHANGELOG.md, docs/quickstarts/snippets/n3dr/DOWNLOAD.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> build: [#467] Resolve 'GLIBC_2.34 not found in snapcraft' issue.

Taskfile.yml, build/package/snap/snapcraft.yaml, cmd/n3dr/root.go, docs/CHANGELOG.md, docs/quickstarts/snippets/n3dr/DOWNLOAD.md, internal/app/n3dr/artifactsv2/count/artifacts_test.go, internal/app/n3dr/artifactsv2/upload/upload_test.go, internal/app/n3dr/config/repository/repository_test.go, internal/app/n3dr/config/security/anonymous_test.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> feat: [#459] Display how long N3DR was running.

internal/app/n3dr/config/user/user_test.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#493] Resolve issue in integration test.

Taskfile.yml, build/package/snap/snapcraft.yaml, docs/CHANGELOG.md, docs/quickstarts/snippets/n3dr/DOWNLOAD.md, internal/app/n3dr/artifactsv2/upload/upload.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#495] Upload issues due to incomplete regex.

cmd/n3dr/root.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#485] Resolve defer issue in time now.

.github/dependabot.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#499] Add default reviewer 030 to dependabot PRs.

.github/workflows/gomod-go-version-updater.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: [#535] Go mod updater go mod tidy

.github/workflows/release.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> build: [#561] Revert to sventaro upload action 2.7.0

.github/workflows/release.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> build: [#561] Write repo permission required to push docker image

.github/dependabot.yml
Aggregate github-actions and docker Dependabot updates.
=> build(fix): Aggregate github-actions and docker Dependabot updates
